     services:
       - type: web
         name: foodfella-backend
         env: node
         buildCommand: npm install
         startCommand: npm start
         envVars:
           - key: NODE_ENV
             value: production